export const GET_RIDES = 'GET_RIDES';
export const ADD_RIDE = 'ADD_RIDE';
export const CREATE_RIDE_SUCCESS = 'CREATE_RIDE_SUCCESS';
export const CREATE_RIDE_STARTED = 'CREATE_RIDE_STARTED';
export const CREATE_RIDE_FAILED = 'CREATE_RIDE_FAILED';

// MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';


// AUTH CONSTANTS
export const ADD_USER = 'ADD_USER';
export const GET_USER = 'GET_USER';
export const LOG_OUT = 'LOG_OUT';
export const CHECK_SESSION = 'CHECK_SESSION';
export const ADD_AUTH_ERROR_MSG = 'ADD_AUTH_ERROR_MSG';
export const DELETE_AUTH_ERROR_MSG = 'DELETE_AUTH_ERROR_MSG';
export const ADD_AUTH_SUCCESS_MSG = 'ADD_AUTH_SUCCESS_MSG';
