export const GET_RIDES = 'GET_RIDES';
export const ADD_RIDE = 'ADD_RIDE';

// MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// export const GET_CONTACT = 'GET_CONTACT';

// export const UPDATE_CONTACT = 'UPDATE_CONTACT';

// AUTH CONSTANTS
export const ADD_USER = 'ADD_USER';
export const GET_USER = 'GET_USER';
export const POST_REGISTRATION_ERROR = 'POST_REGISTRATION_ERROR';
export const DELETE_REGISTRATION_ERROR = 'DELETE_REGISTRATION_ERROR';
