export const GET_RIDES_SUCCESS = 'GET_RIDES_SUCCESS';
export const GET_RIDES_STARTED = 'GET_RIDES_STARTED';
export const GET_RIDES_FAILED = 'GET_RIDES_FAILED';
export const ADD_RIDE = 'ADD_RIDE';
export const CREATE_RIDE_SUCCESS = 'CREATE_RIDE_SUCCESS';
export const CREATE_RIDE_STARTED = 'CREATE_RIDE_STARTED';
export const CREATE_RIDE_FAILED = 'CREATE_RIDE_FAILED';

// MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';


// AUTH CONSTANTS
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const LOG_OUT = 'LOG_OUT';
export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
